import { doc, getDoc } from "firebase/firestore";
import { db } from "./firebaseConfig";
import { Platform } from "react-native";

export const FALLBACK_APPS = [
  {
    name: "Spin the Wheel : Pick for me",
    description: "Spin the wheel to decide fun topics, games, meals, or challenges!",
    icon: "https://destyastudio.com/apps/spin-the-wheel/icon.png",
    androidUrl: "https://destyastudio.com/products/spin-the-wheel",
    iosUrl: "https://destyastudio.com/products/spin-the-wheel",
    isAvailableOnIOS: true,
    show: true,
  },
  {
    name: "AI Icebreaker: Question Games",
    description: "Play icebreaker card games, couples questions, party truths or dares!",
    icon: "https://destyastudio.com/apps/question-games/icon.png",
    androidUrl: "https://destyastudio.com/products/question-games",
    iosUrl: "https://destyastudio.com/products/question-games",
    isAvailableOnIOS: true,
    show: true,
  },
  {
    name: "Cheesy Lines: So Bad, It Works",
    description: "Cheesy, funny, and cute pickup lines that actually work!",
    icon: "https://destyastudio.com/apps/cheezylines/icon.png",
    androidUrl: "https://destyastudio.com/products/cheezylines",
    iosUrl: "https://destyastudio.com/products/cheezylines",
    isAvailableOnIOS: true,
    show: true,
  },
  {
    name: "Trivia Quest AI: Fun Quiz Game",
    description: "Trivia quiz generated by AI to test your knowledge in any category!",
    icon: "https://destyastudio.com/apps/trivia-quest-ai/icon.png",
    androidUrl: "https://destyastudio.com/products/trivia-quest-ai",
    iosUrl: "https://destyastudio.com/products/trivia-quest-ai",
    isAvailableOnIOS: true,
    show: true,
  },
];

const filterAppsByPlatform = (apps) => {
  return apps.filter(app => {
    if (!app.show) return false;
    
    // Exclude CodeRespite itself
    const isCodeRespite = (app.androidUrl && app.androidUrl.includes("code-respite")) ||
                          (app.iosUrl && app.iosUrl.includes("code-respite")) ||
                          (app.name && app.name.toLowerCase().includes("coderespite"));
    if (isCodeRespite) return false;
    
    if (Platform.OS === 'ios') {
      return app.isAvailableOnIOS && app.iosUrl;
    } else if (Platform.OS === 'android') {
      return app.androidUrl;
    }
    
    return true;
  });
};

export const getMoreApps = async () => {
  try {
    const moreAppsRef = doc(db, "config", "moreApps");
    const docSnap = await getDoc(moreAppsRef);

    if (docSnap.exists()) {
      const data = docSnap.data();
      const apps = data.apps || [];
      const filtered = filterAppsByPlatform(apps);
      return filtered.length > 0 ? filtered : filterAppsByPlatform(FALLBACK_APPS);
    } else {
      console.log("No moreApps config found, returning fallback apps");
      return filterAppsByPlatform(FALLBACK_APPS);
    }
  } catch (error) {
    console.error("Error fetching more apps, returning fallback:", error);
    return filterAppsByPlatform(FALLBACK_APPS);
  }
};
